nome=input ("Digite um funcinário: ")
empresa=input("Digite a instituição: ")
qtde_funcionarios=int(input("Digite a qtd de funcinários: "))
mediaMensalidade=float(input("Digite a média da mensalidade: "))
print(nome + " trabalha na empresa " + empresa)
print("Possui: ", qtde_funcionarios, " funcinários. ")
print("A média da mensalidade é de: " + str(mediaMensalidade))
print("================Verifique os tipos de dados abaixo:================")
print("O tipo de dado váriavel [nome] é: ", type(nome))
print("O tipo de dado váriavel [empresa] é: ", type(empresa))
print("O tipo de dado váriavel [qtde_funcionarios] é: ", type(qtde_funcionarios))
print("O tipo de dado váriavel [mediaMensalidade] é: ", type(mediaMensalidade))